volumes:
  volumes:
    driver: bridge

networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network

services:
  mysql-db:
    image: mysql:lts

    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=donnees
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=Kv/MyBclvuWZt3B0bupIOEGf9yio0Ykviz5omr/QlfQ=
      - MYSQL_ROOT_PASSWORD=Kv/MyBclvuWZt3B0bupIOEGf9yio0Ykviz5omr/QlfQ=
    networks:
      - spring-boot-mysql-network
    volumes:
      - ./MySQL/volume:/etc/mysql/conf.d /MySQL/volume

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 3s
      timeout: 30s

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: meschebajordy/pmt-backend:v1
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
  
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/donnees
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=Kv/MyBclvuWZt3B0bupIOEGf9yio0Ykviz5omr/QlfQ=
    networks:
      - spring-boot-mysql-network

  frontend:
        build:
          context: frontend
          dockerfile: Dockerfile
        image: meschebajordy/pmt-frontend:v1

        ports:
          - "4200:80"
        expose:
        - 80
        volumes:
          - .:/app
          - /app/node_modules
          
    
        networks:
          - spring-boot-mysql-network   