name: CICD-Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:lts
        env:
          MYSQL_DATABASE: donnees
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3308:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-start-period=30s 
          --health-retries=5 
          --health-timeout=10s
    env:
      SKIP_TESTS: 'false'
      SPRING_PROFILES_ACTIVE: pmt
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/donnees
      SPRING_DATASOURCE_USERNAME: ${{ secrets.MYSQL_USER }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Install Dependencies
        working-directory: backend
        run: mvn clean install -DskipTests

      - name: Run Backend Tests
        if: env.SKIP_TESTS != 'true'
        working-directory: backend
        run: mvn test -X

      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-backend:v1 ./backend

      - name: Save Docker Image
        run: docker save -o backend-image.tar ${{ secrets.DOCKER_USERNAME }}/spring-boot-backend:v1

      - name: Upload Backend Image
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend-image.tar

  push-image-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Backend Image
        uses: actions/download-artifact@v4
        with:
          name: backend-image
          path: .

      - name: Load Docker Image
        run: docker load -i backend-image.tar

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-backend:v1 

  build-frontend:
    runs-on: ubuntu-latest
    env:
      SKIP_TESTS: 'false'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build --configuration=production

      - name: Vérification du dossier dist
        run: |
          if [ ! -d "frontend/dist" ]; then
            echo "Erreur: Le dossier dist n'a pas été généré. Vérifiez angular.json et les logs de build."
            exit 1
          fi

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Run Frontend Tests
        if: env.SKIP_TESTS != 'true'
        working-directory: frontend
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-frontend:v1 ./frontend

      - name: Save Docker Image
        run: docker save -o frontend-image.tar ${{ secrets.DOCKER_USERNAME }}/angular-frontend:v1

      - name: Upload Frontend Image
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend-image.tar

  push-image-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Frontend Image
        uses: actions/download-artifact@v4
        with:
          name: frontend-image
          path: .

      - name: Load Docker Image
        run: docker load -i frontend-image.tar

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/angular-frontend:v1
