name: CI-pipeline

on:
  push:
    branches: 
    - main
  pull_request:
    branches:  
    - main

    
jobs:
  build:
    runs-on: ubuntu-latest  
    services:
      docker:
        image: docker:20.10.0
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#Build des images du frontend et du backend 
      - name: Build des images du frontend et du backend 
        run: docker-compose -f docker-compose.yml build

#Tests frontend
      - name: Run frontend  tests 
        run: docker-compose run frontend npm run test  -- --watch=false --browsers=ChromeHeadless

#Tests backend
      - name: Run backend  tests 
        run: docker-compose run backend ./mvnw test 

#Deploiement 
      - name: Push docker images 
        run: docker-compose push
    if: success()